disabled_rules:
    - trailing_whitespace
    - nesting
    - redundant_optional_initialization
    - unused_closure_parameter
    - identifier_name
    - line_length
    - function_parameter_count
    - function_body_length
    - discouraged_direct_init

opt_in_rules:
    - empty_count
    - empty_string
    - closure_end_indentation
    - let_var_whitespace
    
excluded:
  - Peekabook/Global/Extension/UILabel+.swift
  - Peekabook/Application/AppDelegate.swift
  - Peekabook/Application/SceneDelegate.swift

file_length:
    warning: 800
    error: 1000

type_name:
    min_length: 2
    
identifier_name:
    min_length: 2

force_cast: warning
